### ISSUE TITLE
Админка. Пользователи

### ISSUE THREAD

**Issue by isklv** [komuchto/site#1]
Начнем с админки. Подготовим таблицу для пользователей. Пользователи имеют возможность регистрироваться и привязывать аккаунты соц сетей. Нужна ли регистрация без соц сетей?

**Comment by fallart** [comment]
думаю нужна, даже сейчас не все пользуются соцсетями

**Comment by isklv** [comment]
Почта у всех есть. Есть возможность не вводить пароли, а авторизовываться через email.

**Comment by fallart** [comment]
имеешь в виду через почтовые сервисы?

**Comment by isklv** [comment]
Да. Здесь так сделано. http://auto.komuchto.ru/users/login

**Comment by DzhuKirova** [comment]
Да, регистрация без соцсетей нужна.

**Comment by komuchto** [comment]
в соседней ветке написал примерно о том же :)
в топку регистрацию! Верификации за глаза хватит, только подумать и об смс верификации с сот номером вместо емаил

**Comment by ubd1** [comment]
Всем привет, теперь я с вами. Какая помощь нужна от меня. Готов принимать решения

**Comment by isklv** [comment]
Закрываю
