### ISSUE TITLE
Дополнительные и обязательные поля для пользователей

### ISSUE THREAD

**Issue by isklv** [komuchto/site#10]
В расширении нет возможности получить email. Над этим я поработаю. 
Вопрос: Какие поля сделать дополнительные и обязательные?

**Comment by errordnk** [comment]
нет обязательных полей
есть способ захода на сайт (соц сети, емаил, телефон), с опцией профиля в личном кабинете, который человек может заполнить, а может и не заполнять, если заполняет в профиле телефон или емейл, то они должны проверяться посылкой кода

**Comment by isklv** [comment]
Почту нужно добавлять или оставлять страницу пользователя и имя?
