### ISSUE TITLE
Рубрикатор

### ISSUE THREAD

**Issue by isklv** [komuchto/site#11]
Что делать с рубрикатором? Брать из art_rub?

**Comment by errordnk** [comment]
в чистом виде, нет
нужно будет разобрать рубрики братские могилы, с последующей обратной сборкой для газеты
здоровье туризм знакомства торжества = в отдельные рубрики, с Наташей еще прикинем по другим могилкам
и понятие действия будем упразднять, оставим только продаю. лишь для недвижимости будет признак - сдаю
то есть остается рубрика и подрубрика

**Comment by isklv** [comment]
Жду рубрикатор
