### ISSUE TITLE
Показ баннеров

### ISSUE THREAD

**Issue by fallart** [komuchto/site#23]
как у нас будет реализована система размещения баннеров?

**Comment by errordnk** [comment]
один баннер-растяжка вверху
3-4 баннера-небоскреба справа, 3 есть всегда, четвертый, если есть место по высоте на больших экранах

**Comment by fallart** [comment]
а по какому принципу будет отображение баннера на конкретном месте? я так понял как на старом сайте привязки конкретного баннера к конкретному месту не будет

**Comment by errordnk** [comment]
и еще одно место при показе одного объявления, растяжка внизу

**Comment by errordnk** [comment]
будет продажа конкретного места, но дорого

**Comment by errordnk** [comment]
будет продажа показов
продажа показов на конкретном месте
продажа любого места по времени
продажа конкретного места по времени

**Comment by errordnk** [comment]
на каждое место будет очередь-ротация

**Comment by errordnk** [comment]
такого, что это только мое место, не будет, ну если только очень за дорого
