### ISSUE TITLE
Работа с рекламодателями

### ISSUE THREAD

**Issue by fallart** [komuchto/site#27]
публикация баннеров на сайте у нас будет возможна только через отдел рекламы или же будет возможность публикации через сайт?
например: авторизовываются, добавляют баннер, выбирают тариф, оплачивают и их баннер добавляется в ротацию

**Comment by isklv** [comment]
Моё мнение. Нужно оба варианта учитывать.

**Comment by fallart** [comment]
ну через отдел рекламы то в любом случае будет, я думаю

**Comment by errordnk** [comment]
не для первого варианта сайта, но в дальнейшем почему бы и нет, а скорее даже да

**Comment by fallart** [comment]
мне кажется если с самого начала продумывать и реализовывать ту логику показа баннеров, которая планируется, то сам кабинет к этому делу прикрутить - дело не сложное
