### ISSUE TITLE
Зарегистрироватья и получить все ключи для авторизации через сервисы

### ISSUE THREAD

**Issue by isklv** [komuchto/site#8]
https://github.com/komuchto/site/blob/master/komuchto/protected/config/main.php

**Comment by isklv** [comment]
Здесь подвижки есть?

**Comment by errordnk** [comment]
Артур, тебе флаг в руки, собрать все ключи для komuchto во всех соцсетях

**Comment by fallart** [comment]
а регистрировать на какой емейл?
во всех соцсетях надо зарегистрироваться от имени комучто

**Comment by isklv** [comment]
В прикреплённом конфигурационном файле есть все сервисы, который ключи требуют. Ключики не требуют google и yandex

**Comment by fallart** [comment]
я так понял речь идет о  oAuth?

**Comment by errordnk** [comment]
не только об oAuth
речь идет и о социальных сетях, в каких то мы уже зарегистрированы (вконтакте, фейсбук, твиттер) в каких то еще нет, нужно выяснить пассворд для komuchto там где мы есть и зарегистрировать там где нас нет

**Comment by fallart** [comment]
а у кого это нужно выяснить?

**Comment by DzhuKirova** [comment]
ВКонтакте страница зарегистрирована на личный телефон Светланы Володькиной, причем с понедельника будет создаваться новая группа Кому Что, соответственно, пароли надо сделать общие и почту привязать корпоративную. В мейле аккаунт завязан на почту komuchto.saratov@mail.ru, в одноклассах - personal.komuchto@gmail.com, в твиттере - personal.komuchto@gmail.com

**Comment by fallart** [comment]
от одноклассников, мейла и вконтакте у меня пароли есть, можете выслать мне на почту пароль от твиттера?
и вопрос по вконтакте: мне создавать новый аккаунт привязанный к емейлу компании или оставлять старый?

**Comment by DzhuKirova** [comment]
Адрес почты? По контакту: оставляем этот, он завязан на рабочий сотовый, а не на личный. Вопрос: не проблема, что все аккаунты на почту персонал.комучто? Это удобно будет?

**Comment by fallart** [comment]
3fallart3@gmail.com
все данные, которые есть пришлите, пожалуйста
буду к ним привязывать

**Comment by DzhuKirova** [comment]
Артур, чтобы зайти вКонтакт, перед номером телефона ставь +7

**Comment by komuchto** [comment]
во всех социальных сетях и прочих сторонних ресурсах использовать: 
емейл editor@komuchto.ru
пароль rjvexnj если требует усложнить, то цифра 2 на конце
телефон 89379719754

**Comment by fallart** [comment]
вписал в код то что есть, остались вк и одноклассники
и для регистрации через mail нужно их html в корень скинуть

**Comment by fallart** [comment]
все соц сети что от меня требовались - вписал

**Comment by isklv** [comment]
Закрываю
